# Generated by Django 4.2.11 on 2024-03-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
