# Generated by Django 4.2.11 on 2024-03-11 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printblog', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
    ]
